name: 'IcePAK'
description: 'Pushes built image to polar server'
author: Zack Siri
branding:
  color: blue
  icon: terminal
runs:
  using: "composite"
  steps:
    - name: Create Mix Directory
      run: |
        mkdir -p ~/.mix
      shell: bash

    - name: Setup Alpine
      uses: jirutka/setup-alpine@v1
      with:
        branch: ${{ inputs.alpine }}
        packages: |
          zip
          tar
          sudo
          cmake
          elixir
          coreutils
          alpine-sdk
        volumes: |
          /home/runner/.mix:/home/runner/.mix

    - name: Prepare Path
      run: |
        echo "/home/runner/.mix/escripts" >> $GITHUB_PATH
      shell: alpine.sh {0}

    - name: Cache IcePAK
      id: cache-pakman
      uses: actions/cache@v4
      with:
        path: ~/.mix
        key: ${{ runner.arch }}-icepak-0.1.0

    - name: Install Pakman
      if: steps.cache-pakman.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix escript.install hex icepak 0.1.0 --force
      shell: bash
      env:
        MIX_ENV: prod