name: 'IcePAK'
description: 'Pushes built image to polar server'
inputs: 
  polar_endpoint:
    description: "The endpoint for polar image server."
    required: true
    default: "https://images.opsmaru.com"
runs:
  using: "composite"
  steps:
    - name: Create Mix Directory
      run: |
        mkdir -p ~/.mix
      shell: bash

    - uses: erlef/setup-beam@v1
      with:
        otp-version: "26.2.1"
        elixir-version: "1.15.7"

    - name: Cache IcePAK
      id: cache-pakman
      uses: actions/cache@v4
      with:
        path: ~/.mix
        key: ${{ runner.arch }}-icepak-0.1.0

    - name: Install Pakman
      if: steps.cache-pakman.outputs.cache-hit != 'true'
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix escript.install hex icepak 0.1.0 --force
      shell: bash
      env:
        MIX_ENV: prod